In [1]:
# Load everything 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as mlt
import seaborn as sb 
import cufflinks as cfk

In [3]:
#Importing the dataset 
df=pd.read_csv('social_media_dopamine_productivity.csv')
df

,participant_id,data_source,synthetic_flag,age,age_group,gender,race_ethnicity,nationality,country_of_residence,education_level,...,mood_dependency_on_sm,withdrawal_attempt_count,longest_detox_days,detox_relapse_reason,severity_stage,productivity_decline_score,dopamine_dysregulation_index,digital_wellbeing_score,sm_addiction_risk_score,notes
0,P0001,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,...,Yes,9,2,3,Boredom,Critical,8.8,9.2,2.1,9.5
1,P0002,synthetic_ai,1,17,13-17,Male,East Asian,Chinese,China,High school,...,Yes,10,1,1,Curiosity,Critical,9.5,9.8,1.5,9.8
2,P0003,synthetic_ai,1,15,13-17,Female,Black/African,Nigerian,Nigeria,High school,...,Yes,8,2,5,Boredom,Severe,8.0,8.5,2.8,9.0
3,P0004,synthetic_ai,1,19,18-22,Male,White/Caucasian,American,USA,High school,...,Yes,9,3,7,Boredom,Severe,7.8,8.2,2.9,8.8
4,P0005,synthetic_ai,1,18,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,4,FOMO,Critical,9.0,9.3,2.0,9.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,synthetic_ai,1,24,23-27,Female,White/Caucasian,British,UK,Undergraduate,...,Yes,9,3,6,Comparison,Severe,7.8,8.2,2.9,8.7
296,P0297,synthetic_ai,1,35,28-35,Male,Black/African,Senegalese,Senegal,Undergraduate,...,Sometimes,4,5,18,FOMO,Early,4.8,5.4,5.4,5.8
297,P0298,synthetic_ai,1,20,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,3,FOMO,Critical,9.2,9.5,2.0,9.7
298,P0299,synthetic_ai,1,46,36-49,Male,East Asian,Filipino,Philippines,Undergraduate,...,Rarely,3,6,28,Boredom,None/Minimal,3.2,3.8,7.0,4.0
299,P0300,synthetic_ai,1,22,18-22,Male,Black/African,Nigerian,Nigeria,Undergraduate,...,Yes,9,2,3,Boredom,Critical,9.0,9.4,2.1,9.6

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 66 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   participant_id                    300 non-null    str
 1   data_source                       300 non-null    str
 2   synthetic_flag                    300 non-null    int64
 3   age                               300 non-null    int64
 4   age_group                         300 non-null    str
 5   gender                            300 non-null    str
 6   race_ethnicity                    300 non-null    str
 7   nationality                       300 non-null    str
 8   country_of_residence              300 non-null    str
 9   education_level                   300 non-null    str
 10  employment_status                 300 non-null    str
 11  occupation_category               300 non-null    str
 12  relationship_status               300 non-null    str
 13  avg_daily_sm_hours                300 non-null    float64
 14  years_on_social_media             300 non-null    int64
 15  primary_platform                  300 non-null    str
 16  secondary_platform                297 non-null    str
 17  daily_check_frequency             300 non-null    str
 18  first_check_of_day                300 non-null    str
 19  late_night_scrolling              300 non-null    str
 20  sm_during_work_study              300 non-null    str
 21  sm_during_meals                   300 non-null    str
 22  notifications_always_on           300 non-null    str
 23  scroll_without_purpose            300 non-null    str
 24  doomscrolling_frequency           300 non-null    str
 25  content_type_consumed             300 non-null    str
 26  avg_daily_screen_time_hours       300 non-null    float64
 27  avg_sleep_hours                   300 non-null    float64
 28  sleep_quality                     300 non-null    str
 29  exercise_frequency                300 non-null    str
 30  avg_work_study_hours_per_day      300 non-null    float64
 31  dopamine_rush_feel_score          300 non-null    int64
 32  reward_seeking_behavior           300 non-null    int64
 33  fomo_score                        300 non-null    int64
 34  comparison_to_others_score        300 non-null    int64
 35  validation_seeking_score          300 non-null    int64
 36  boredom_to_phone_reflex           300 non-null    str
 37  inability_to_delay_gratification  300 non-null    str
 38  attention_span_minutes            300 non-null    int64
 39  deep_work_duration_minutes        300 non-null    int64
 40  task_switching_frequency          300 non-null    str
 41  difficulty_starting_tasks         300 non-null    str
 42  difficulty_maintaining_focus      300 non-null    str
 43  mind_wandering_during_work        300 non-null    str
 44  productivity_self_rating          300 non-null    int64
 45  tasks_completed_per_day           300 non-null    int64
 46  work_quality_self_rating          300 non-null    int64
 47  creative_output_frequency         300 non-null    str
 48  reading_duration_minutes_per_day  300 non-null    int64
 49  memory_recall_difficulty          300 non-null    str
 50  learning_retention_difficulty     300 non-null    str
 51  decision_fatigue_score            300 non-null    int64
 52  mental_fog_frequency              300 non-null    str
 53  irritability_when_offline         300 non-null    str
 54  anxiety_when_phone_unavailable    300 non-null    int64
 55  restlessness_score                300 non-null    int64
 56  mood_dependency_on_sm             300 non-null    str
 57  withdrawal_attempt_count          300 non-null    int64
 58  longest_detox_days                300 non-null    int64
 59  detox_relapse_reason              300 non-null    int64
 60  severity_stage                    211 non-null    str
 61  productivity_decline_score        300 non-null    str
 62  dopamine_dysregulation_index      300 non-null    float64
 63  digital_wellbeing_score           300 non-null    float64
 64  sm_addiction_risk_score           300 non-null    float64
 65  notes                             300 non-null    float64
dtypes: float64(8), int64(20), str(38)
memory usage: 239.0 KB

In [7]:
#QUe-> Print its first 5 rows, the total number of rows and columns (shape), and the list of all column names.
df.head()

,participant_id,data_source,synthetic_flag,age,age_group,gender,race_ethnicity,nationality,country_of_residence,education_level,...,mood_dependency_on_sm,withdrawal_attempt_count,longest_detox_days,detox_relapse_reason,severity_stage,productivity_decline_score,dopamine_dysregulation_index,digital_wellbeing_score,sm_addiction_risk_score,notes
0,P0001,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,...,Yes,9,2,3,Boredom,Critical,8.8,9.2,2.1,9.5
1,P0002,synthetic_ai,1,17,13-17,Male,East Asian,Chinese,China,High school,...,Yes,10,1,1,Curiosity,Critical,9.5,9.8,1.5,9.8
2,P0003,synthetic_ai,1,15,13-17,Female,Black/African,Nigerian,Nigeria,High school,...,Yes,8,2,5,Boredom,Severe,8.0,8.5,2.8,9.0
3,P0004,synthetic_ai,1,19,18-22,Male,White/Caucasian,American,USA,High school,...,Yes,9,3,7,Boredom,Severe,7.8,8.2,2.9,8.8
4,P0005,synthetic_ai,1,18,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,4,FOMO,Critical,9.0,9.3,2.0,9.6

In [9]:
df.shape

(300, 66)

In [10]:
df.columns

Index(['participant_id', 'data_source', 'synthetic_flag', 'age', 'age_group',
       'gender', 'race_ethnicity', 'nationality', 'country_of_residence',
       'education_level', 'employment_status', 'occupation_category',
       'relationship_status', 'avg_daily_sm_hours', 'years_on_social_media',
       'primary_platform', 'secondary_platform', 'daily_check_frequency',
       'first_check_of_day', 'late_night_scrolling', 'sm_during_work_study',
       'sm_during_meals', 'notifications_always_on', 'scroll_without_purpose',
       'doomscrolling_frequency', 'content_type_consumed',
       'avg_daily_screen_time_hours', 'avg_sleep_hours', 'sleep_quality',
       'exercise_frequency', 'avg_work_study_hours_per_day',
       'dopamine_rush_feel_score', 'reward_seeking_behavior', 'fomo_score',
       'comparison_to_others_score', 'validation_seeking_score',
       'boredom_to_phone_reflex', 'inability_to_delay_gratification',
       'attention_span_minutes', 'deep_work_duration_minutes',
       'task_switching_frequency', 'difficulty_starting_tasks',
       'difficulty_maintaining_focus', 'mind_wandering_during_work',
       'productivity_self_rating', 'tasks_completed_per_day',
       'work_quality_self_rating', 'creative_output_frequency',
       'reading_duration_minutes_per_day', 'memory_recall_difficulty',
       'learning_retention_difficulty', 'decision_fatigue_score',
       'mental_fog_frequency', 'irritability_when_offline',
       'anxiety_when_phone_unavailable', 'restlessness_score',
       'mood_dependency_on_sm', 'withdrawal_attempt_count',
       'longest_detox_days', 'detox_relapse_reason', 'severity_stage',
       'productivity_decline_score', 'dopamine_dysregulation_index',
       'digital_wellbeing_score', 'sm_addiction_risk_score', 'notes'],
      dtype='str')

In [16]:
#Que-> Find the average (mean), minimum, and maximum values of avg_daily_sm_hours
average=df['avg_daily_sm_hours'].mean()
print(average)
minimum= df['avg_daily_sm_hours'].min()
print(minimum)
maximum=df['avg_daily_sm_hours'].max()
print(maximum)

4.03
0.5
9.0

In [17]:
#QUe-> Find how many participants use each primary_platform
df['primary_platform'].value_counts()

primary_platform
Instagram        95
Facebook         89
YouTube          50
LinkedIn         26
TikTok           21
WeChat           12
Twitter/X         5
Douyin/TikTok     1
Reddit            1
Name: count, dtype: int64

In [20]:
#Que-> Filter and display all rows where avg_daily_sm_hours is greater than 6 hours and gender is 'Female'
df[(df['avg_daily_sm_hours']>6 )&(df['gender']=='Female')]

,participant_id,data_source,synthetic_flag,age,age_group,gender,race_ethnicity,nationality,country_of_residence,education_level,...,mood_dependency_on_sm,withdrawal_attempt_count,longest_detox_days,detox_relapse_reason,severity_stage,productivity_decline_score,dopamine_dysregulation_index,digital_wellbeing_score,sm_addiction_risk_score,notes
0,P0001,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,...,Yes,9,2,3,Boredom,Critical,8.8,9.2,2.1,9.5
2,P0003,synthetic_ai,1,15,13-17,Female,Black/African,Nigerian,Nigeria,High school,...,Yes,8,2,5,Boredom,Severe,8.0,8.5,2.8,9.0
4,P0005,synthetic_ai,1,18,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,4,FOMO,Critical,9.0,9.3,2.0,9.6
8,P0009,synthetic_ai,1,22,18-22,Female,South Asian,Bangladeshi,Bangladesh,Undergraduate,...,Yes,10,2,3,Validation seeking,Critical,9.2,9.4,2.0,9.7
14,P0015,synthetic_ai,1,20,18-22,Female,East Asian,South Korean,South Korea,Undergraduate,...,Yes,10,1,2,Validation seeking,Critical,9.5,9.7,1.8,9.9
18,P0019,synthetic_ai,1,16,13-17,Female,Hispanic/Latino,Colombian,Colombia,High school,...,Yes,9,2,4,Boredom,Critical,9.0,9.3,2.1,9.6
20,P0021,synthetic_ai,1,17,13-17,Female,White/Caucasian,American,USA,High school,...,Yes,9,2,3,Validation seeking,Critical,9.2,9.5,2.0,9.7
22,P0023,synthetic_ai,1,19,18-22,Female,Black/African,Ghanaian,Ghana,High school,...,Yes,8,2,4,Boredom,Severe,7.8,8.2,2.9,8.7
28,P0029,synthetic_ai,1,17,13-17,Female,Middle Eastern,Turkish,Turkey,High school,...,Yes,9,2,3,Comparison,Critical,9.0,9.3,2.2,9.6
32,P0033,synthetic_ai,1,22,18-22,Female,South Asian,Indian,India,Undergraduate,...,Yes,10,1,2,Validation seeking,Critical,9.4,9.6,1.9,9.8
34,P0035,synthetic_ai,1,16,13-17,Female,Black/African,Nigerian,Nigeria,High school,...,Yes,10,1,1,Boredom,Critical,9.5,9.8,1.5,9.9
40,P0041,synthetic_ai,1,19,18-22,Female,East Asian,Vietnamese,Vietnam,High school,...,Yes,8,2,4,Boredom,Severe,7.8,8.2,2.9,8.7
42,P0043,synthetic_ai,1,21,18-22,Female,Hispanic/Latino,Venezuelan,Venezuela,Undergraduate,...,Yes,9,2,4,Comparison,Severe,7.8,8.2,2.9,8.7
46,P0047,synthetic_ai,1,16,13-17,Female,White/Caucasian,Canadian,Canada,High school,...,Yes,9,2,3,Validation seeking,Critical,9.2,9.5,2.0,9.7
50,P0051,synthetic_ai,1,21,18-22,Female,Middle Eastern,Lebanese,Lebanon,Undergraduate,...,Yes,9,2,5,Comparison,Severe,7.8,8.2,2.9,8.7
52,P0053,synthetic_ai,1,19,18-22,Female,South Asian,Bangladeshi,Bangladesh,High school,...,Yes,10,2,3,Validation seeking,Critical,9.4,9.6,1.8,9.8
56,P0057,synthetic_ai,1,17,13-17,Female,South Asian,Indian,India,High school,...,Yes,10,1,1,Validation seeking,Critical,9.5,9.8,1.5,9.9
58,P0059,synthetic_ai,1,18,18-22,Female,East Asian,Thai,Thailand,High school,...,Yes,9,2,3,Boredom,Critical,9.0,9.3,2.2,9.6
241,P0242,synthetic_ai,1,38,36-49,Female,East Asian,Chinese,China,Postgraduate,...,Yes,9,3,7,Dopamine rush,Critical,8.8,9.2,2.2,9.5
243,P0244,synthetic_ai,1,27,23-27,Female,Black/African,American,USA,Undergraduate,...,Yes,10,2,3,Boredom/Depression,Critical,9.2,9.5,2.0,9.7
247,P0248,synthetic_ai,1,16,13-17,Female,South Asian,Indian,India,High school,...,Yes,10,1,1,Validation seeking,Critical,9.8,10.0,1.2,10.0
250,P0251,synthetic_ai,1,18,18-22,Female,White/Caucasian,American,USA,High school,...,Yes,10,1,1,Validation seeking,Critical,9.9,10.0,1.1,10.0
254,P0255,synthetic_ai,1,22,18-22,Female,Black/African,Nigerian,Nigeria,Undergraduate,...,Yes,9,2,3,Comparison/Validation,Critical,9.3,9.6,1.9,9.8
258,P0259,synthetic_ai,1,17,13-17,Female,East Asian,Japanese,Japan,High school,...,Yes,10,2,3,Validation seeking,Critical,9.4,9.6,1.9,9.8
260,P0261,synthetic_ai,1,21,18-22,Female,South Asian,Bangladeshi,Bangladesh,Undergraduate,...,Yes,10,1,2,Validation seeking,Critical,9.6,9.8,1.4,9.9
270,P0271,synthetic_ai,1,21,18-22,Female,White/Caucasian,Canadian,Canada,Undergraduate,...,Yes,9,2,3,FOMO,Critical,9.2,9.5,2.0,9.7
279,P0280,synthetic_ai,1,17,13-17,Female,Hispanic/Latino,Venezuelan,Venezuela,High school,...,Yes,10,1,1,Validation seeking,Critical,9.6,9.9,1.4,9.9
283,P0284,synthetic_ai,1,18,18-22,Female,East Asian,Vietnamese,Vietnam,High school,...,Yes,9,2,3,Comparison,Critical,9.0,9.3,2.2,9.6
291,P0292,synthetic_ai,1,19,18-22,Female,Middle Eastern,Saudi,Saudi Arabia,High school,...,Yes,10,2,3,Validation seeking,Critical,9.4,9.6,1.8,9.8
293,P0294,synthetic_ai,1,16,13-17,Female,East Asian,South Korean,South Korea,High school,...,Yes,10,1,1,Validation seeking,Critical,9.9,10.0,1.1,10.0
295,P0296,synthetic_ai,1,24,23-27,Female,White/Caucasian,British,UK,Undergraduate,...,Yes,9,3,6,Comparison,Severe,7.8,8.2,2.9,8.7
297,P0298,synthetic_ai,1,20,18-22,Female,Hispanic/Latino,Mexican,Mexico,High school,...,Yes,9,2,3,FOMO,Critical,9.2,9.5,2.0,9.7

In [21]:
#Que-> Group the data by gender and calculate the average attention_span_minutes for each group
df.groupby('gender')['attention_span_minutes'].mean()

gender
Female        26.331081
Male          29.103448
Non-binary    16.428571
Name: attention_span_minutes, dtype: float64

In [26]:
#Que-> How would you create a new column representing non-work screen time , 
df['non-work-ScreenTime']=df['avg_daily_screen_time_hours']-df['avg_work_study_hours_per_day']
df[['avg_daily_screen_time_hours']['avg_work_study_hours_per_day']['non-work-Screentime']].head()

<>:3: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
/var/folders/xv/hsz4y13j7jd2_cbvgdphpb9w0000gn/T/ipykernel_33474/883219689.py:3: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  df[['avg_daily_screen_time_hours']['avg_work_study_hours_per_day']['non-work-Screentime']].head()

TypeError: list indices must be integers or slices, not str